/**
 * 
 */
$(document).ready(function(){
    $("button.remove").click(function(){
        $.post("init.do",{
              operate:"remove",
              id:$("button.remove").attr("name")
            },
            function(){
                alert("ajax");
            });
    });
});